###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@testmail.com",
    "password": "pass"
}



###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "pass"
}



###


POST http://localhost:5000/auth/logout
Content-Type: application/json

{

}




###


GET http://localhost:5000/


###

POST http://localhost:5000/blogs/new
Content-Type: application/json

{
    "filename": "test.txt"
}




