###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@testmail.com",
    "password": "pass"
}



###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}



###


POST http://localhost:5000/auth/logout
Content-Type: application/json

{

}




###


GET http://localhost:5000/profiles/me


###

POST http://localhost:5000/blogs/newtitle
Content-Type: application/json

{
    "title": "test.txt"
}




